/*
  Eventually this kind of routers should be 
  autogenerated based on some type of objects
  modeling system. 
*/

import { Router } from "express"
import { responseError, response } from "../response.js";
import { getDb } from "../db/index.js";

export const HostsRouter = Router()

// /api/v1/hosts
HostsRouter.get("/", async (req, res) => {
  const db = await getDb("host")
  const entries = await db.getAll()
  response(res, { entries }, "Stored hosts")
})



